import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from "react"
import styles from '../styles/Home.module.css'


export default function Home() {
  const [body, setBody] = useState<string>("")
  const [url, setUrl] = useState("")
  const [loading, setLoading] = useState(false)

  const handleInput = async () => {
    if(url && url.length > 10) {
      setLoading(true)
      const data = await fetch("/api/basic", {
        method:"POST",
        body: JSON.stringify({url: url})
      })
      const res = await data.text();
      setBody(res)
      setLoading(false)
    }
  }
  return (
    <>
      <Head>
        <title>New Renderer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading && <div className={styles.loader}></div>}
      {!loading && <main className={styles.main}>
        <div className={styles.inputContainer}>
          <input 
            className={styles.input}
            placeholder='Enter your URL' 
            onChange={(e:React.ChangeEvent<HTMLInputElement>) => setUrl(e.target.value)} 
          />
          <button type='submit' onClick={handleInput} className={styles.button}>Submit</button>
        </div>
        <div dangerouslySetInnerHTML={{ __html: body }}>
        </div>
      </main>}
    </>
  )
}
